;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.Ability.Attack.One",NewTagName="Character.Ability.Attack.FirstStrike")
+GameplayTagRedirects=(OldTagName="Character.Ability.Attack.Three",NewTagName="Character.Ability.Attack.SecondStrike")
+GameplayTagRedirects=(OldTagName="Character.Ability.Attack.Two",NewTagName="Character.Ability.Attack.ThirdStrike")
+GameplayTagRedirects=(OldTagName="Character.Ability.Attack.FirstStrike",NewTagName="Character.Ability.Attack.Light")
+GameplayTagRedirects=(OldTagName="Character.Ability.Recovery.SelfHeal",NewTagName="Character.Ability.Recovery.Heal")
+GameplayTagRedirects=(OldTagName="Character.Ability.Mobility.Move",NewTagName="Character.Ability.Mobility.Dodge")
+GameplayTagRedirects=(OldTagName="Ability.CrimsonVail",NewTagName="Ability.CrimsonVial")
+GameplayTagList=(Tag="Ability.AIDeath",DevComment="")
+GameplayTagList=(Tag="Ability.CrimsonVial",DevComment="")
+GameplayTagList=(Tag="Ability.Energize",DevComment="")
+GameplayTagList=(Tag="Ability.HitResponse",DevComment="")
+GameplayTagList=(Tag="Ability.Look",DevComment="")
+GameplayTagList=(Tag="Ability.Move",DevComment="")
+GameplayTagList=(Tag="Ability.Resurrection",DevComment="")
+GameplayTagList=(Tag="Ability.Tranquility",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Attack.Basic",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Attack.Light",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dash",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dodge",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dodge.Backward",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dodge.Forward",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dodge.Left",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.Dodge.Right",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Mobility.HomeTeleport",DevComment="")
+GameplayTagList=(Tag="Character.Ability.Recovery.Heal",DevComment="")
+GameplayTagList=(Tag="Character.Status.Alive",DevComment="")
+GameplayTagList=(Tag="Character.Status.InCombat",DevComment="")
+GameplayTagList=(Tag="Character.Status.Resting",DevComment="")
+GameplayTagList=(Tag="Stat.Armor",DevComment="")
+GameplayTagList=(Tag="Stat.AttackPower",DevComment="")
+GameplayTagList=(Tag="Stat.Death",DevComment="")
+GameplayTagList=(Tag="Stat.Energy",DevComment="")
+GameplayTagList=(Tag="Stat.Haste",DevComment="")
+GameplayTagList=(Tag="Stat.Health",DevComment="")
+GameplayTagList=(Tag="Stat.Kill",DevComment="")
+GameplayTagList=(Tag="Stat.Recovery",DevComment="")
+GameplayTagList=(Tag="Stat.SoulForce",DevComment="")

